### ISSUE TITLE
Клиент на Linux

### ISSUE THREAD

**Issue by MelyukhovDmitrii** [suai-os-2019/ot-task4-MelyukhovDmitrii#2]
Написать клиент на Linux для тестов на [https://travis-ci.org/](url)

**Comment by MelyukhovDmitrii** [comment]
Клиент на Linux добавлен [https://github.com/suai-os-2019/ot-task4-MelyukhovDmitrii/commit/1a0e9d0b6c5f5e313ea65956791f199600e519db](url)

**Comment by markpolyak** [comment]
1a0e9d0b6c5f5e313ea65956791f199600e519db
